repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: just-clippy
        name: just clippy
        entry: just clippy
        language: system
        pass_filenames: false

      - id: cargo-fmt
        name: cargo fmt
        entry: bash -c 'for dir in client server shared; do cd $dir; cargo fmt; cd ..; done'
        language: system
        pass_filenames: false

      - id: cargo-check
        name: cargo check
        entry: bash -c 'for dir in client server shared; do cd $dir; cargo check; cd ..; done'
        language: system
        pass_filenames: false

      - id: just-build
        name: just build
        entry: just build
        language: system
        pass_filenames: false

      - id: just-build-release
        name: just build-release
        entry: just build-release
        language: system
        pass_filenames: false
